-- Seed realistic pharmaceutical distributors for StockUp AI
-- Matching therapeutic categories in items table

DELETE FROM suppliers;

INSERT INTO suppliers (
    id, name, contact_person, phone, email, address, city, state, status,
    unit_cost, avg_lead_time_days, lead_time_std_dev_days, performance_score,
    fulfilled_orders, supplied_categories
) VALUES
(
    gen_random_uuid()::text,
    'McKesson Health Distribution',
    'Sarah Jenkins',
    '+1-415-555-0192',
    'orders@mckessonhealth.com',
    '1 Post St, 28th Floor',
    'San Francisco',
    'CA',
    'Active',
    18.50,
    2.5,
    0.6,
    97.0,
    420,
    'General Medicine, Insulin [CS], Insulin Analog [EPC], Anti-Inflammatory Agents, Corticosteroid Hormone Receptor Agonists [MoA]'
),
(
    gen_random_uuid()::text,
    'AmerisourceBergen Logistics',
    'Marcus Vance',
    '+1-610-555-0143',
    'logistics@amerisourcebergen.com',
    '1 West First Ave, Conshohocken Suite 300',
    'Conshohocken',
    'PA',
    'Active',
    19.20,
    3.0,
    0.5,
    98.0,
    512,
    'General Medicine, Penicillin-class Antibacterial [EPC], Decreased Cell Wall Integrity [PE], Antibacterial, Anti-epileptic Agent [EPC]'
),
(
    gen_random_uuid()::text,
    'Cardinal Health Solutions',
    'Elena Rodriguez',
    '+1-614-555-0118',
    'supply@cardinalhealth.com',
    '7000 Cardinal Place',
    'Dublin',
    'OH',
    'Active',
    17.80,
    2.8,
    0.7,
    96.0,
    388,
    'General Medicine, Corticosteroid Hormone Receptor Agonists [MoA], Central Nervous System Stimulant [EPC], Angiotensin 2 Receptor Antagonists [MoA]'
),
(
    gen_random_uuid()::text,
    'Lilly Logistics Direct',
    'David Thornton',
    '+1-317-555-0187',
    'orders@lillylogistics.com',
    'Lilly Corporate Center, Suite 400',
    'Indianapolis',
    'IN',
    'Active',
    24.50,
    2.0,
    0.4,
    99.0,
    310,
    'Insulin [CS], Insulin Analog [EPC], G-Protein-linked Receptor Interactions [MoA], General Medicine'
),
(
    gen_random_uuid()::text,
    'Pfizer Global Distribution',
    'Rachel Adams',
    '+1-212-555-0120',
    'distribution@pfizerglobal.com',
    '66 Hudson Blvd E, Floor 14',
    'New York',
    'NY',
    'Active',
    22.00,
    3.2,
    0.6,
    95.0,
    460,
    'Penicillin-class Antibacterial [EPC], Anti-Inflammatory Agents, Full Opioid Agonists [MoA], Decreased Cell Wall Integrity [PE]'
),
(
    gen_random_uuid()::text,
    'MedLife Pharma Distributors',
    'Alice Smith',
    '+1-212-555-0165',
    'alice.smith@medlifepharma.com',
    '450 Lexington Ave, Suite 1200',
    'New York',
    'NY',
    'Active',
    14.50,
    4.0,
    0.8,
    91.0,
    215,
    'General Medicine, Anti-Inflammatory Agents, Cholinergic Nicotinic Agonist [EPC], Allergens [CS]'
),
(
    gen_random_uuid()::text,
    'BioGen Therapeutics Supply',
    'Evan Wright',
    '+1-858-555-0149',
    'supply@biogentherapeutics.com',
    '10240 Science Center Dr',
    'San Diego',
    'CA',
    'Active',
    28.00,
    2.2,
    0.5,
    98.5,
    275,
    'Insulin [CS], Insulin Analog [EPC], Blood Coagulation Factor [EPC], Breast Cancer Resistance Protein Inhibitors [MoA]'
),
(
    gen_random_uuid()::text,
    'Apex Rx Logistics',
    'Brian O''Connor',
    '+1-312-555-0177',
    'support@apexrxlogistics.com',
    '300 S Riverside Plaza, Suite 900',
    'Chicago',
    'IL',
    'Active',
    15.20,
    3.5,
    0.9,
    92.0,
    198,
    'Angiotensin 2 Receptor Antagonists [MoA], Adrenergic alpha1-Agonists [MoA], Adrenergic alpha-Agonists [MoA], General Medicine'
),
(
    gen_random_uuid()::text,
    'NovaCare Pharmaceutical Network',
    'Jennifer Wu',
    '+1-617-555-0182',
    'contact@novacarepharma.com',
    '500 Boylston St, 16th Floor',
    'Boston',
    'MA',
    'Active',
    16.90,
    3.8,
    1.0,
    89.0,
    160,
    'Anti-epileptic Agent [EPC], Central Nervous System Stimulant [EPC], Atypical Antipsychotic [EPC], Benzodiazepine [EPC]'
),
(
    gen_random_uuid()::text,
    'Zenith Pharma Direct',
    'George Miller',
    '+1-303-555-0199',
    'orders@zenithpharmadirect.com',
    '1700 Lincoln St, Suite 2200',
    'Denver',
    'CO',
    'Active',
    13.80,
    4.5,
    1.1,
    87.0,
    185,
    'Decreased Respiratory Secretion Viscosity [PE], Histamine H1 Receptor Antagonists [MoA], General Medicine, Anti-Inflammatory Agents'
),
(
    gen_random_uuid()::text,
    'OmniMed Express Distribution',
    'Teresa Ramirez',
    '+1-214-555-0134',
    'orders@omnimedexpress.com',
    '2001 Ross Ave, Suite 700',
    'Dallas',
    'TX',
    'Active',
    20.10,
    2.9,
    0.7,
    94.0,
    320,
    'Blood Coagulation Factor [EPC], Actively Acquired Immunity [PE], Kinase Inhibitor [EPC], G-Protein-linked Receptor Interactions [MoA]'
),
(
    gen_random_uuid()::text,
    'PrimeRx Medical Wholesale',
    'Kevin Patel',
    '+1-404-555-0156',
    'sales@primerxwholesale.com',
    '3344 Peachtree Rd NE, Suite 1100',
    'Atlanta',
    'GA',
    'Active',
    12.80,
    5.2,
    1.2,
    85.0,
    140,
    'General Medicine, Cytochrome P450 2D6 Inhibitors [MoA], Sigma-1 Agonist [EPC], Anti-Inflammatory Agents'
),
(
    gen_random_uuid()::text,
    'HealthFirst Supply Chain',
    'Diana Prince',
    '+1-206-555-0168',
    'supply@healthfirstsupplies.com',
    '1201 3rd Ave, Suite 1800',
    'Seattle',
    'WA',
    'Active',
    16.40,
    3.4,
    0.8,
    93.0,
    240,
    'Insulin [CS], Corticosteroid Hormone Receptor Agonists [MoA], Penicillin-class Antibacterial [EPC]'
),
(
    gen_random_uuid()::text,
    'CarePlus Healthcare Logistics',
    'Charlie Davis',
    '+1-617-555-0191',
    'charlie@careplusmed.com',
    '100 High St, 9th Floor',
    'Boston',
    'MA',
    'Inactive',
    26.50,
    6.5,
    1.5,
    81.0,
    55,
    'General Medicine, Full Opioid Agonists [MoA]'
);
